workspace = { members = ["libs/lib-neural-network", "libs/lib-simulation-game"] }
[package]
name = "learn-to-fly-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
